### ISSUE TITLE
JSDOMParser should handle uppercase tag names

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#101]
Sample test case:

```js
describe("Tag name case handling", function() {
  it("should handle lowercase tag names", function() {
    var html = "<div>plop</div>";
    var doc = new JSDOMParser().parse(html);
    expect(doc.firstChild.tagName).eql("DIV");
    expect(doc.firstChild.localName).eql("div");
  });

  it("should handle uppercase tag names", function() {
    var html = "<DIV>plop</DIV>";
    var doc = new JSDOMParser().parse(html);
    expect(doc.firstChild.tagName).eql("DIV");
    expect(doc.firstChild.localName).eql("div");
  });
});
```

The first test passes but the second test fails:

```
JSDOMParser error: expected '</div>'

  1) Tag name case handling should handle uppercase tag names:
     TypeError: Cannot read property 'tagName' of null
      at Context.<anonymous> (/Users/niko/Sites/readability/test/test-jsdomparser.js:282:26)
      at callFn (/Users/niko/Sites/readability/node_modules/mocha/lib/runnable.js:266:21)
      at Test.Runnable.run (/Users/niko/Sites/readability/node_modules/mocha/lib/runnable.js:259:7)
      at Runner.runTest (/Users/niko/Sites/readability/node_modules/mocha/lib/runner.js:387:10)
      at /Users/niko/Sites/readability/node_modules/mocha/lib/runner.js:470:12
      at next (/Users/niko/Sites/readability/node_modules/mocha/lib/runner.js:312:14)
      at /Users/niko/Sites/readability/node_modules/mocha/lib/runner.js:322:7
      at next (/Users/niko/Sites/readability/node_modules/mocha/lib/runner.js:257:23)
      at Object._onImmediate (/Users/niko/Sites/readability/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by n1k0** [comment]
Fixed by #100 (56b45e3fa9141619f02b73e39ab42107751ce1c8)
