### ISSUE TITLE
Error Cannot read property 'parsingMode' of null

### ISSUE THREAD

**Issue by bazo** [mozilla/readability#246]
when using readability from node.js this error gets thrown

    Error Cannot read property 'parsingMode' of null TypeError: Cannot read property 'parsingMode' of null
    at Object.exports.jsdom (project_path\node_modules\readability\node_modules\jsdom\lib\jsdom.js:66:14)
    at createDocWithHTMLParser (project_path\node_modules\readability\lib\readability.js:2164:20)
    at Object.parse (project_path\node_modules\readability\lib\readability.js:2176:13)
    at IncomingMessage.<anonymous> (project_path/main.js:34:15)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

latest version from npm

**Comment by bazo** [comment]
hm, npm installs different package named readability
