### ISSUE TITLE
Got: Cannot read property 'firstElementChild' of undefined

### ISSUE THREAD

**Issue by xJeremie** [mozilla/readability#376]
I'm trying to use this lib by
```js
var fs = require("fs");

function readFile(filePath) {
  return fs.readFileSync(filePath, {encoding: "utf-8"}).trim();
}

var html = readFile("./test/test-pages/cnn/source.html")

// console.log(html)

var readability = require("./index");
var Readability = readability.Readability;
var JSDOMParser = readability.JSDOMParser;

var article = new Readability({}, html).parse();
```
But got
```
/*
D:\readability\Readability.js:2032                                                     
    if (typeof this._doc.documentElement.firstElementChild === "undefined") {              
                                        ^                                                  
                                                                                           
TypeError: Cannot read property 'firstElementChild' of undefined                           
    at Readability.parse (D:\readability\Readability.js:2032:41)                       
    at Object.<anonymous> (D:\readability\test.js:15:41)                               
    at Module._compile (module.js:571:32)                                                  
    at Object.Module._extensions..js (module.js:580:10)                                    
    at Module.load (module.js:488:32)                                                      
    at tryModuleLoad (module.js:447:12)                                                    
    at Function.Module._load (module.js:439:3)                                             
    at Module.runMain (module.js:605:10)                                                   
    at run (bootstrap_node.js:427:7)                                                       
    at startup (bootstrap_node.js:148:9)                                                   
*/
```

Is this a library problem or I do something wrong?

The `npm test` is run fine!

**Comment by gijsk** [comment]
As noted in https://github.com/mozilla/readability#usage , the second argument to the `Readability` constructor is a `Document` instance (ie DOM object), not a string of HTML. You need to use `JSDOMParser` or `jsdom` or some other DOM utility to create a DOM from the HTML first.

**Comment by xJeremie** [comment]
@gijsk Thank you! But with this code.
```js
var url1 = 'https://www.freecodecamp.com/the-fastest-web-page-on-the-internet';
var url2 = 'http://google.com/';

var request = require('request');
request(url1, function (error, response, body) {
    if (error) {
        console.log("ERR");
    } else {
        var html_text = body.trim();
        console.log(html_text);

        var soup = new JSDOMParser().parse(html_text);
    }
});
```
using `url1`, it's suceess. but using `url2` it throw a lot of error.
```
[...]
JSDOMParser error: Error reading attribute his;var aa, expecting '"'

JSDOMParser error: Error reading attribute unction(a,b,c,d){d, expecting '"'

JSDOMParser error: Error reading attribute ||{};d._sn, expecting '"'

JSDOMParser error: Error reading attribute "cfg",b,c].join(".");window.gbar.logger.ml(a,d)};var g, expecting '"'

JSDOMParser error: Error reading attribute indow.gbar, expecting '"'

JSDOMParser error: Error reading attribute indow.gbar||{},h, expecting '"'

JSDOMParser error: Error reading attribute indow.gbar.i, expecting '"'

JSDOMParser error: Error reading attribute indow.gbar.i||{},ba;function _tvn(a,b){a, expecting '"'

JSDOMParser error: Error reading attribute arseInt(a,10);return isNaN(a)?b:a}function _tvf(a,b){a, expecting '"'

JSDOMParser error: Error reading attribute arseFloat(a);return isNaN(a)?b:a}function _tvv(a){return!!a}function p(a,b,c){(c||g)[a], expecting '"'

JSDOMParser error: Error reading attribute }g.bv, expecting '"'

JSDOMParser error: Error reading attribute +b;if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent(d,c);else{var f, expecting '"'

JSDOMParser error: Error reading attribute [d];a[d], expecting '"'

JSDOMParser error: Error reading attribute unction(){var a, expecting '"'

JSDOMParser error: Error reading attribute .apply(this,arguments),b, expecting '"'

JSDOMParser error: Error reading attribute .apply(this,arguments);return void 0, expecting '"'

JSDOMParser error: Error reading attribute a?b:void 0, expecting '"'

JSDOMParser error: Error reading attribute b?a:b&&a}}}var da, expecting '"'

JSDOMParser error: Error reading attribute unction(a){return function(){return g.bv.m, expecting '"'

JSDOMParser error: Error reading attribute a}},ea, expecting '"'

JSDOMParser error: Error reading attribute a(1),fa, expecting '"'

JSDOMParser error: Error reading attribute a(2);p("sb",ea);p("kn",fa);h.a, expecting '"'
[...]
```

**Comment by gijsk** [comment]
Yes, JSDOMParser will only read valid XHTML. It's not a "real" DOM parser. Consider using `jsdom` instead.

**Comment by gijsk** [comment]
I updated the README to attempt to clarify this a bit more.

**Comment by xJeremie** [comment]
@gijsk 
I really appreciate your help. A BIG THANKS to you! 🤓

**Comment by bittlingmayer** [comment]
We are long-time users but still hit this issue occasionally.

The issue is that certain versions of Readability work only with certain versions of JSDOM.  But because we declare the JSDOM dependency explicitly instead of Readability declaring it, it is too easy to have a mismatch.

It does seem like asking for more trouble that `parse` throws an a cryptic error because of bad input to a different function that was called earlier.

**Comment by bittlingmayer** [comment]
In particular, I could be doing something wrong, but I cannot find even an old version of the jsdom npm that works with the current version of this repo, which makes it hard for us to fork it to add changes that we may want to contribute.

**Comment by gijsk** [comment]
@bittlingmayer Thanks for the comments. Are you using current readability tip? Perhaps we broke something with #439, for which it would help if you included more details (in a new issue please!). With the information included here, I'm not really sure how to help.

Regarding the error message, I guess we could try to stub-test for the document being passed? I can file a separate issue for that.

**Comment by bittlingmayer** [comment]
@gijsk Yes, from the tip.  Our package.json dependencies included:

```
    "jsdom": "^11.6.0",
    "readability": "github:mozilla/readability"
```

To get it to work I had to change it to:  
```
    "jsdom": "11.9.0",
    "readability": "github:mozilla/readability#3c76104adb00eb9897517e6be6c74c6c05918dfe"
```
The version is not the latest that works nor anything else special, just one I copied from the output of `npm list` from a repo that was working.
