### ISSUE TITLE
alternativeCandidateAncestors[ancestorIndex].includes is not a function

### ISSUE THREAD

**Issue by sammoes** [mozilla/readability#382]
refers to:
listsContainingThisAncestor += Number(alternativeCandidateAncestors[ancestorIndex].includes(parentOfTopCandidate));
on line 900

This error was thrown by simply checking out the repo and running
 mocha test/test-*.js

  1) Test pages ehow-1 jsdom "before all" hook:
     TypeError: alternativeCandidateAncestors[ancestorIndex].includes is not a function
      at Object.Readability._grabArticle (/home/sam/iFox/readability-master/Readability.js:900:98)
      at Object.Readability.parse (/home/sam/iFox/readability-master/Readability.js:2053:31)
      at Context.<anonymous> (/home/sam/iFox/readability-master/test/test-readability.js:65:27)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:223:21)
      at Hook.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:216:7)
      at next (/usr/lib/nodejs/mocha/lib/runner.js:258:10)
      at Immediate._onImmediate (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  2) Test pages ehow-1 JSDOMParser "before all" hook:
     TypeError: alternativeCandidateAncestors[ancestorIndex].includes is not a function
      at Object.Readability._grabArticle (/home/sam/iFox/readability-master/Readability.js:900:98)
      at Object.Readability.parse (/home/sam/iFox/readability-master/Readability.js:2053:31)
      at Context.<anonymous> (/home/sam/iFox/readability-master/test/test-readability.js:65:27)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:223:21)
      at Hook.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:216:7)
      at next (/usr/lib/nodejs/mocha/lib/runner.js:258:10)
      at Immediate._onImmediate (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  3) Test pages ehow-2 jsdom "before all" hook:
     TypeError: alternativeCandidateAncestors[ancestorIndex].includes is not a function
      at Object.Readability._grabArticle (/home/sam/iFox/readability-master/Readability.js:900:98)
      at Object.Readability.parse (/home/sam/iFox/readability-master/Readability.js:2053:31)
      at Context.<anonymous> (/home/sam/iFox/readability-master/test/test-readability.js:65:27)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:223:21)
      at Hook.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:216:7)
      at next (/usr/lib/nodejs/mocha/lib/runner.js:258:10)
      at Immediate._onImmediate (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

  4) Test pages ehow-2 JSDOMParser "before all" hook:
     TypeError: alternativeCandidateAncestors[ancestorIndex].includes is not a function
      at Object.Readability._grabArticle (/home/sam/iFox/readability-master/Readability.js:900:98)
      at Object.Readability.parse (/home/sam/iFox/readability-master/Readability.js:2053:31)
      at Context.<anonymous> (/home/sam/iFox/readability-master/test/test-readability.js:65:27)
      at callFn (/usr/lib/nodejs/mocha/lib/runnable.js:223:21)
      at Hook.Runnable.run (/usr/lib/nodejs/mocha/lib/runnable.js:216:7)
      at next (/usr/lib/nodejs/mocha/lib/runner.js:258:10)
      at Immediate._onImmediate (/usr/lib/nodejs/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by gijsk** [comment]
What version of node is this, and does it have es6 support?

**Comment by gijsk** [comment]
Per https://node.green/ , looks like you want at least node 6.5. Closing this now that I've updated package.json.
