### ISSUE TITLE
Strip bgcolor attributes

### ISSUE THREAD

**Issue by tigt** [mozilla/readability#383]
Example: https://www.jwz.org/doc/linuxvideo.html

I use Reader Mode to reformat old pages on my phone, and it usually works well. Some pages like the above, Scott McCloud's, etc. with heavy use of `<td bgcolor>` clash with the Dark theme, becoming illegible:

![Screenshot of a page in Firefox's Reader Mode, with white text clashing on a yellow background.](https://user-images.githubusercontent.com/8072522/28942847-c8a76aae-786a-11e7-8e79-87640878fa9a.png)

This could be fixed by removing `bgcolor` attributes in Readability.js, but also in the applied stylesheet with `[bgcolor] { background-color: transparent }` or something. Which is preferable?

**Comment by gijsk** [comment]
We should remove the attributes, rather than requiring all consumers to update stylesheets. Note that bgcolor isn't the only relevant attribute, there's also 'align' and maybe others. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1151150 (but this is the right place for an issue with the `Readability.js` code, which this is. :-)

**Comment by tigt** [comment]
Gotcha. Some quick research later, here are the similar presentational attributes I could find:

* **`<table>`:** `align`, `bgcolor`, `border`, `cellspacing`, `cellpadding`, `frame`, `rules`, and `width`
* **`<tr>`:** `align`, `bgcolor`, and `valign`
* **`<td>`:** `align`, `bgcolor`, `valign`, and `width`

Does that seem correct? I don't think these attributes sans `width` are acceptable anywhere, so they could be combined into a global removelist instead of scoped to their individual table elements.

**Comment by gijsk** [comment]
Yep, that list seems comprehensive to me, and your suggestion also sounds sane to me. We could probably remove them in `_cleanStyles`. A testcase would also be a good thing to have - we could probably hand-write something that uses these attributes, or pull something off jwz's or a similar site, I guess, with `generate-testcase.js`. Would it be possible for you to create a pull request?

**Comment by tigt** [comment]
I'll do my best!

**Comment by tigt** [comment]
I've submitted [a strawman pull request](https://github.com/mozilla/readability/pull/385); I've not worked with test runners before, so I'm unsure what to do next. Running the suggested `mocha test/test-*.js` produces:

<details>
<pre>
  775 passing (52s)
  53 failing

  1) Test pages 002 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  2) Test pages 002 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  3) Test pages ars-1 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  4) Test pages ars-1 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  5) Test pages blogger jsdom should extract expected content:

      AssertionError: expected 4 to deeply equal 5
      + expected - actual

      -4
      +5
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  6) Test pages blogger JSDOMParser should extract expected content:

      AssertionError: expected 4 to deeply equal 5
      + expected - actual

      -4
      +5
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  7) Test pages breitbart jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  8) Test pages breitbart JSDOMParser should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  9) Test pages cnet jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  10) Test pages cnet JSDOMParser should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  11) Test pages cnn jsdom should extract expected content:

      AssertionError: expected 2 to deeply equal 3
      + expected - actual

      -2
      +3
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  12) Test pages cnn JSDOMParser should extract expected content:

      AssertionError: expected 2 to deeply equal 3
      + expected - actual

      -2
      +3
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  13) Test pages daringfireball-1 jsdom should extract expected content:

      AssertionError: expected 2 to deeply equal 3
      + expected - actual

      -2
      +3
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  14) Test pages daringfireball-1 JSDOMParser should extract expected content:

      AssertionError: expected 2 to deeply equal 3
      + expected - actual

      -2
      +3
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  15) Test pages ehow-2 jsdom should extract expected content:

      AssertionError: expected 3 to deeply equal 4
      + expected - actual

      -3
      +4
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  16) Test pages ehow-2 JSDOMParser should extract expected content:

      AssertionError: expected 3 to deeply equal 4
      + expected - actual

      -3
      +4
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  17) Test pages gmw jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  18) Test pages gmw JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  19) Test pages iab-1 jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  20) Test pages iab-1 JSDOMParser should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  21) Test pages keep-images jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  22) Test pages keep-images JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  23) Test pages links-in-tables jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  24) Test pages links-in-tables JSDOMParser should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  25) Test pages medium-1 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  26) Test pages medium-1 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  27) Test pages medium-2 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  28) Test pages medium-2 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  29) Test pages medium-3 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  30) Test pages medium-3 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  31) Test pages msn jsdom should extract expected content:

      AssertionError: expected 5 to deeply equal 6
      + expected - actual

      -5
      +6
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  32) Test pages msn JSDOMParser should extract expected content:

      AssertionError: expected 5 to deeply equal 6
      + expected - actual

      -5
      +6
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  33) Test pages pixnet jsdom should extract expected content:

      AssertionError: expected 7 to deeply equal 8
      + expected - actual

      -7
      +8
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  34) Test pages pixnet JSDOMParser should extract expected content:

      AssertionError: expected 7 to deeply equal 8
      + expected - actual

      -7
      +8
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  35) Test pages qq jsdom should extract expected content:

      AssertionError: expected 2 to deeply equal 3
      + expected - actual

      -2
      +3
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  36) Test pages qq JSDOMParser should extract expected content:

      AssertionError: expected 2 to deeply equal 3
      + expected - actual

      -2
      +3
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  37) Test pages salon-1 jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  38) Test pages salon-1 JSDOMParser should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  39) Test pages svg-parsing jsdom should extract expected content:

      AssertionError: expected 6 to deeply equal 7
      + expected - actual

      -6
      +7
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  40) Test pages svg-parsing JSDOMParser should extract expected content:

      AssertionError: expected 6 to deeply equal 7
      + expected - actual

      -6
      +7
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  41) Test pages table-style-attributes jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  42) Test pages table-style-attributes jsdom should extract expected excerpt:

      AssertionError: expected 'linux usability' to deeply equal 'linux usability\n    ...or, why do I bother. © 2002, 2003\n        Jamie Zawinski'
      + expected - actual

      -linux usability
      +linux usability
      +    ...or, why do I bother. © 2002, 2003
      +        Jamie Zawinski
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at Context.<anonymous> (test/test-readability.js:156:40)

  43) Test pages table-style-attributes JSDOMParser "before all" hook:
     TypeError: Cannot read property 'documentElement' of null
      at Readability.parse (Readability.js:2047:25)
      at Context.<anonymous> (test/test-readability.js:65:27)

  44) Test pages wikipedia jsdom should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  45) Test pages wikipedia JSDOMParser should extract expected content:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  46) Test pages yahoo-1 jsdom should extract expected content:

      AssertionError: expected 3 to deeply equal 4
      + expected - actual

      -3
      +4
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  47) Test pages yahoo-1 JSDOMParser should extract expected content:

      AssertionError: expected 3 to deeply equal 4
      + expected - actual

      -3
      +4
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  48) Test pages yahoo-2 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  49) Test pages yahoo-2 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  50) Test pages yahoo-3 jsdom should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  51) Test pages yahoo-3 JSDOMParser should extract expected content:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  52) Test pages youth jsdom should extract expected content:

      AssertionError: expected 6 to deeply equal 7
      + expected - actual

      -6
      +7
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)

  53) Test pages youth JSDOMParser should extract expected content:

      AssertionError: expected 6 to deeply equal 7
      + expected - actual

      -6
      +7
      
      at Assertion.assertEql (node_modules/chai/lib/chai/core/assertions.js:473:10)
      at Assertion.ctx.(anonymous function) [as eql] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at test/test-readability.js:132:50
      at traverseDOM (test/test-readability.js:39:10)
      at Context.<anonymous> (test/test-readability.js:113:7)
</pre>
</details>

**Comment by gijsk** [comment]
Ah, yep. So the test failures are actually pointing to a problem, but the test output is clearly not helpful. Sorry about that. It looks like your patch removes the `width` attribute everywhere - also on non-table nodes. So the test is failing because we're no longer matching the expected output for a number of pages - it looks like all of them have `<img>` nodes where a `width` attribute is set. If you adjust your patch / pull request such that `width` attributes are ignored, I think the test failures should go away. :-)

**Comment by tigt** [comment]
Makes sense. `width` probably *should* be removed on tabular elements—should I special-case that?

**Comment by gijsk** [comment]
Yeah, specialcasing `width` should be fine. Thanks again for working on this!
