### ISSUE TITLE
Can't require this library in node

### ISSUE THREAD

**Issue by ccorcos** [mozilla/readability#508]
I get an error just for importing.

```js
❯❯❯ node
> require("readability")
TypeError: Cannot read property 'HTMLFrameElement' of undefined
    at /Users/chet/Code/js/download-website/node_modules/readability/lib/readability.js:2223:14
    at Object.<anonymous> (/Users/chet/Code/js/download-website/node_modules/readability/lib/readability.js:2227:3)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Points to this code:

```
//jsdom tweaks
if (!jsdom.applyDocumentFeatures)
(function() {
	//hack for older versions of jsdom when features can't be disabled by API
	var core = jsdom.defaultLevel;
	//disable loading frames
	delete core.HTMLFrameElement.prototype.setAttribute;

	//disable script evaluation
	delete core.HTMLScriptElement.prototype.init;
})();
```

I see your JSDom is version 13.1 and mine is too...

```
❯❯❯ node -v
v11.3.0
❯❯❯ m info
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
```

Any ideas?

**Comment by ccorcos** [comment]
Well I deleted those lines of code and it worked...

**Comment by ccorcos** [comment]
Man, this library is a read struggle.

```
import * as readability from "readability"
const article = readability.parse(document)
```

```
(node:34084) UnhandledPromiseRejectionWarning: TypeError: theHtml.replace is not a function
    at Object.parse (/Users/chet/Code/js/download-website/node_modules/readability/lib/readability.js:2408:21)
    at /Users/chet/Code/js/download-website/main.ts:33:30
    at step (/Users/chet/Code/js/download-website/main.ts:32:23)
    at Object.next (/Users/chet/Code/js/download-website/main.ts:13:53)
    at /Users/chet/Code/js/download-website/main.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/chet/Code/js/download-website/main.ts:3:12)
    at main2 (/Users/chet/Code/js/download-website/main.ts:72:12)
    at Object.<anonymous> (/Users/chet/Code/js/download-website/main.ts:39:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```

**Comment by gijsk** [comment]
`Readability.js` in this repo doesn't have a line 2400, or any of the code you're referencing, so you must have meant to file this issue somewhere else.

**Comment by gijsk** [comment]
This package is not available on npm at this time, see #43 .

**Comment by ccorcos** [comment]
haha well that explains it!

**Comment by janzheng** [comment]
for others struggling with this, "npm install github:mozilla/readability" or "yarn add github:mozilla/readability" and should do the trick

**Comment by thiswillbeyourgithub** [comment]
> for others struggling with this, "npm install github:mozilla/readability" or "yarn add github:mozilla/readability" and should do the trick

worked for me, thanks. Careful to not add a "/" at the end like me  : 
`npm install github:mozilla/readability\ works
`npm install github:mozilla/readability/` doesn't

**Comment by ralyodio** [comment]
how do I import in esm?
