### ISSUE TITLE
JSDOMparser fails to parse nymag.com

### ISSUE THREAD

**Issue by jakubriedl** [mozilla/readability#649]
While testing fix for #594 I found out that the url https://nymag.com/intelligencer/2020/05/polarization-republicans-democracy-ezra-klein-book-review.html cannot be added as testcase because JSDOMparser fails to parse it.

```
> node test/generate-testcase.js "nymag-1" "https://nymag.com/intelligencer/2020/05/polarization-republicans-democracy-ezra-klein-book-review.html"

JSDOMParser error: Error reading attribute v, expecting '"'

JSDOMParser error: Error reading attribute .indexOf("--\x3e");if(v>, expecting '"'

JSDOMParser error: Error reading attribute ){t.shouldKeepComment&&t.comment(e.substring(4,v),c,c+v+3),C(v+3);continue}}if(So.test(e)){var h, expecting '"'

JSDOMParser error: Error reading attribute .indexOf("]>");if(h>, expecting '"'

JSDOMParser error: Error reading attribute ){C(h+2);continue}}var m, expecting '"'

JSDOMParser error: Error reading attribute .match(Ao);if(m){C(m[0].length);continue}var y, expecting '"'

JSDOMParser error: Error reading attribute .match(ko);if(y){var g, expecting '"'

JSDOMParser error: Error reading attribute ;C(y[0].length),A(y[1],g,c);continue}var _, expecting '"'

JSDOMParser error: Error reading attribute ();if(_){k(_),Mo(_.tagName,e)&&C(1);continue}}var b, expecting '"'

JSDOMParser error: Error reading attribute oid 0,$, expecting '"'

JSDOMParser error: Error reading attribute oid 0,w, expecting '"'

JSDOMParser error: Error reading attribute oid 0;if(d>, expecting '"'

JSDOMParser error: Error reading attribute ){for($, expecting '"'

JSDOMParser error: Error reading attribute .slice(d);!(ko.test($)||Co.test($)||Oo.test($)||So.test($)||(w, expecting '"'

JSDOMParser error: Error reading attribute .indexOf("<",1))<0);)d+, expecting '"'

JSDOMParser error: Error reading attribute ,$, expecting '"'

JSDOMParser error: Error reading attribute .slice(d);b, expecting '"'

JSDOMParser error: Error reading attribute .substring(0,d)}d<0&&(b, expecting '"'

JSDOMParser error: Error reading attribute ),b&&C(b.length),t.chars&&b&&t.chars(b,c-b.length,c)}if(e, expecting '"'

JSDOMParser error: Error reading attribute n){t.chars&&t.chars(e);break}}function C(t){c+, expecting '"'

JSDOMParser error: Error reading attribute ,e, expecting '"'

JSDOMParser error: Error reading attribute .substring(t)}function x(){var t, expecting '"'

JSDOMParser error: Error reading attribute .match(Co);if(t){var n,r,i, expecting '"'

JSDOMParser error: Error reading attribute tagName:t[1],attrs:[],start:c};for(C(t[0].length);!(n, expecting '"'

JSDOMParser error: Error reading attribute .match(xo))&&(r, expecting '"'

JSDOMParser error: Error reading attribute .match(bo)||e.match(_o));)r.start, expecting '"'

JSDOMParser error: Error reading attribute ,C(r[0].length),r.end, expecting '"'

JSDOMParser error: Error reading attribute ,i.attrs.push(r);if(n)return i.unarySlash, expecting '"'

JSDOMParser error: Error reading attribute [1],C(n[0].length),i.end, expecting '"'

JSDOMParser error: Error reading attribute ,i}}function k(e){var n, expecting '"'

JSDOMParser error: Error reading attribute .tagName,c, expecting '"'

JSDOMParser error: Error reading attribute .unarySlash;o&&("p", expecting '"'

JSDOMParser error: Error reading attribute r&&go(n)&&A(r),s(n)&&r, expecting '"'

JSDOMParser error: Error reading attribute n&&A(n));for(var u, expecting '"'

JSDOMParser error: Error reading attribute (n)||!!c,l, expecting '"'

JSDOMParser error: Error reading attribute .attrs.length,f, expecting '"'

JSDOMParser error: Error reading attribute ew Array(l),p, expecting '"'

JSDOMParser error: Error reading attribute ;p<l;p++){var d, expecting '"'

JSDOMParser error: Error reading attribute .attrs[p],v, expecting '"'

JSDOMParser error: Error reading attribute n&&"href", expecting '"'

JSDOMParser error: Error reading attribute d[1]?t.shouldDecodeNewlinesForHref:t.shouldDecodeNewlines;f[p], expecting '"'

JSDOMParser error: Error reading attribute name:d[1],value:Io(v,h)}}u||(i.push({tag:n,lowerCasedTag:n.toLowerCase(),attrs:f,start:e.start,end:e.end}),r, expecting '"'

JSDOMParser error: Error reading attribute ),t.start&&t.start(n,f,u,e.start,e.end)}function A(e,n,o){var a,s;if(null, expecting '"'

JSDOMParser error: Error reading attribute n&&(n, expecting '"'

JSDOMParser error: Error reading attribute ),null, expecting '"'

JSDOMParser error: Error reading attribute o&&(o, expecting '"'

JSDOMParser error: Error reading attribute ),e)for(s, expecting '"'

JSDOMParser error: Error reading attribute .toLowerCase(),a, expecting '"'

JSDOMParser error: Error reading attribute .length-1;a>, expecting '"'

JSDOMParser error: Error reading attribute &&i[a].lowerCasedTag!, expecting '"'

JSDOMParser error: Error reading attribute s;a--);else a, expecting '"'

JSDOMParser error: Error reading attribute ;if(a>, expecting '"'

JSDOMParser error: Error reading attribute ){for(var u, expecting '"'

JSDOMParser error: Error reading attribute .length-1;u>, expecting '"'

JSDOMParser error: Error reading attribute ;u--)t.end&&t.end(i[u].tag,n,o);i.length, expecting '"'

JSDOMParser error: Error reading attribute ,r, expecting '"'

JSDOMParser error: Error reading attribute &&i[a-1].tag}else"br", expecting '"'

JSDOMParser error: Error reading attribute s?t.start&&t.start(e,[],!0,n,o):"p", expecting '"'

JSDOMParser error: Error reading attribute s&&(t.start&&t.start(e,[],!1,n,o),t.end&&t.end(e,n,o))}A()}(e,{warn:Fo,expectHTML:t.expectHTML,isUnaryTag:t.isUnaryTag,canBeLeftOpenTag:t.canBeLeftOpenTag,shouldDecodeNewlines:t.shouldDecodeNewlines,shouldDecodeNewlinesForHref:t.shouldDecodeNewlinesForHref,shouldKeepComment:t.comments,outputSourceRange:t.outputSourceRange,start:function(e,o,a,l,f){var p, expecting '"'

JSDOMParser error: Error reading attribute &&r.ns||Vo(e);q&&"svg", expecting '"'

JSDOMParser error: Error reading attribute p&&(o, expecting '"'

JSDOMParser error: Error reading attribute unction(e){for(var t, expecting '"'

JSDOMParser error: Error reading attribute ],n, expecting '"'

JSDOMParser error: Error reading attribute ;n<e.length;n++){var r, expecting '"'

JSDOMParser error: Error reading attribute [n];pa.test(r.name)||(r.name, expecting '"'

JSDOMParser error: Error reading attribute .name.replace(da,""),t.push(r))}return t}(o));var d,v, expecting '"'

JSDOMParser error: Error reading attribute a(e,o,r);p&&(v.ns, expecting '"'

JSDOMParser error: Error reading attribute ),"style"!, expecting '"'

JSDOMParser error: Error reading attribute (d, expecting '"'

JSDOMParser error: Error reading attribute ).tag&&("script"!, expecting '"'

JSDOMParser error: Error reading attribute d.tag||d.attrsMap.type&&"text/javascript"!, expecting '"'

JSDOMParser error: Error reading attribute d.attrsMap.type)||te()||(v.forbidden, expecting '"'

JSDOMParser error: Error reading attribute 0);for(var h, expecting '"'

JSDOMParser error: Error reading attribute ;h<Ho.length;h++)v, expecting '"'

JSDOMParser error: Error reading attribute o[h](v,t)||v;s||(function(e){null!, expecting '"'

JSDOMParser error: Error reading attribute r(e,"v-pre")&&(e.pre, expecting '"'

JSDOMParser error: Error reading attribute 0)}(v),v.pre&&(s, expecting '"'

JSDOMParser error: Error reading attribute 0)),Uo(v.tag)&&(c, expecting '"'

JSDOMParser error: Error reading attribute 0),s?function(e){var t, expecting '"'

JSDOMParser error: Error reading attribute .attrsList,n, expecting '"'

JSDOMParser error: Error reading attribute .length;if(n)for(var r, expecting '"'

JSDOMParser error: Error reading attribute .attrs, expecting '"'

JSDOMParser error: Error reading attribute ew Array(n),i, expecting '"'

JSDOMParser error: Error reading attribute ;i<n;i++)r[i], expecting '"'

JSDOMParser error: Error reading attribute name:t[i].name,value:JSON.stringify(t[i].value)},null!, expecting '"'

JSDOMParser error: Error reading attribute [i].start&&(r[i].start, expecting '"'

JSDOMParser error: Error reading attribute [i].start,r[i].end, expecting '"'

JSDOMParser error: Error reading attribute [i].end);else e.pre||(e.plain, expecting '"'

JSDOMParser error: Error reading attribute 0)}(v):v.processed||(sa(v),function(e){var t, expecting '"'

JSDOMParser error: Error reading attribute r(e,"v-if");if(t)e.if, expecting '"'

JSDOMParser error: Error reading attribute ,ca(e,{exp:t,block:e});else{null!, expecting '"'

JSDOMParser error: Error reading attribute r(e,"v-else")&&(e.else, expecting '"'

JSDOMParser error: Error reading attribute 0);var n, expecting '"'

JSDOMParser error: Error reading attribute r(e,"v-else-if");n&&(e.elseif, expecting '"'

JSDOMParser error: Error reading attribute )}}(v),function(e){null!, expecting '"'

JSDOMParser error: Error reading attribute r(e,"v-once")&&(e.once, expecting '"'

JSDOMParser error: Error reading attribute 0)}(v)),n||(n, expecting '"'

JSDOMParser error: Error reading attribute ),a?u(v):(r, expecting '"'

JSDOMParser error: Error reading attribute ,i.push(v))},end:function(e,t,n){var o, expecting '"'

JSDOMParser error: Error reading attribute [i.length-1];i.length-, expecting '"'

JSDOMParser error: Error reading attribute ,r, expecting '"'

JSDOMParser error: Error reading attribute [i.length-1],u(o)},chars:function(e,t,n){if(r&&(!q||"textarea"!, expecting '"'

JSDOMParser error: Error reading attribute r.tag||r.attrsMap.placeholder!, expecting '"'

JSDOMParser error: Error reading attribute e)){var i,u,l,f, expecting '"'

JSDOMParser error: Error reading attribute .children;(e, expecting '"'

JSDOMParser error: Error reading attribute ||e.trim()?"script", expecting '"'

JSDOMParser error: Error reading attribute (i, expecting '"'

JSDOMParser error: Error reading attribute ).tag||"style", expecting '"'

JSDOMParser error: Error reading attribute i.tag?e:ra(e):f.length?a?"condense", expecting '"'

JSDOMParser error: Error reading attribute a&&ta.test(e)?"":" ":o?" ":"":"")&&(c||"condense"!, expecting '"'

JSDOMParser error: Error reading attribute a||(e, expecting '"'

JSDOMParser error: Error reading attribute .replace(na," ")),!s&&" "!, expecting '"'

JSDOMParser error: Error reading attribute e&&(u, expecting '"'

JSDOMParser error: Error reading attribute unction(e,t){var n, expecting '"'

JSDOMParser error: Error reading attribute o?po(Po):lo;if(n.test(e)){for(var r,i,o,a, expecting '"'

JSDOMParser error: Error reading attribute ],s, expecting '"'

JSDOMParser error: Error reading attribute ],c, expecting '"'

JSDOMParser error: Error reading attribute .lastIndex, expecting '"'

JSDOMParser error: Error reading attribute ;r, expecting '"'

JSDOMParser error: Error reading attribute .exec(e);){(i, expecting '"'

JSDOMParser error: Error reading attribute .index)>c&&(s.push(o, expecting '"'

JSDOMParser error: Error reading attribute .slice(c,i)),a.push(JSON.stringify(o)));var u, expecting '"'

JSDOMParser error: Error reading attribute r(r[1].trim());a.push("_s("+u+")"),s.push({"@binding":u}),c, expecting '"'

JSDOMParser error: Error reading attribute +r[0].length}return c<e.length&&(s.push(o, expecting '"'

JSDOMParser error: Error reading attribute .slice(c)),a.push(JSON.stringify(o))),{expression:a.join("+"),tokens:s}}}(e))?l, expecting '"'

JSDOMParser error: Error reading attribute type:2,expression:u.expression,tokens:u.tokens,text:e}:" ", expecting '"'

JSDOMParser error: Error reading attribute e&&f.length&&" ", expecting '"'

JSDOMParser error: Error reading attribute f[f.length-1].text||(l, expecting '"'

JSDOMParser error: Error reading attribute type:3,text:e}),l&&f.push(l))}},comment:function(e,t,n){if(r){var i, expecting '"'

JSDOMParser error: Error reading attribute type:3,text:e,isComment:!0};r.children.push(i)}}}),n}(e.trim(),t);!1!, expecting '"'

JSDOMParser error: Error reading attribute t.optimize&&function(e,t){e&&(ha, expecting '"'

JSDOMParser error: Error reading attribute a(t.staticKeys||""),ma, expecting '"'

JSDOMParser error: Error reading attribute .isReservedTag||T,function e(t){if(t.static, expecting '"'

JSDOMParser error: Error reading attribute unction(e){return 2!, expecting '"'

JSDOMParser error: Error reading attribute e.type&&(3, expecting '"'

JSDOMParser error: Error reading attribute e.type||!(!e.pre&&(e.hasBindings||e.if||e.for||d(e.tag)||!ma(e.tag)||function(e){for(;e.parent;){if("template"!, expecting '"'

JSDOMParser error: Error reading attribute (e, expecting '"'

JSDOMParser error: Error reading attribute .parent).tag)return!1;if(e.for)return!0}return!1}(e)||!Object.keys(e).every(ha))))}(t),1, expecting '"'

JSDOMParser error: Error reading attribute t.type){if(!ma(t.tag)&&"slot"!, expecting '"'

JSDOMParser error: Error reading attribute t.tag&&null, expecting '"'

JSDOMParser error: Error reading attribute t.attrsMap["inline-template"])return;for(var n, expecting '"'

JSDOMParser error: Error reading attribute ,r, expecting '"'

JSDOMParser error: Error reading attribute .children.length;n<r;n++){var i, expecting '"'

JSDOMParser error: Error reading attribute .children[n];e(i),i.static||(t.static, expecting '"'

JSDOMParser error: Error reading attribute 1)}if(t.ifConditions)for(var o, expecting '"'

JSDOMParser error: Error reading attribute ,a, expecting '"'

JSDOMParser error: Error reading attribute .ifConditions.length;o<a;o++){var s, expecting '"'

JSDOMParser error: Error reading attribute .ifConditions[o].block;e(s),s.static||(t.static, expecting '"'

JSDOMParser error: Error reading attribute 1)}}}(e),function e(t,n){if(1, expecting '"'

JSDOMParser error: Error reading attribute t.type){if((t.static||t.once)&&(t.staticInFor, expecting '"'

JSDOMParser error: Error reading attribute ),t.static&&t.children.length&&(1!, expecting '"'

JSDOMParser error: Error reading attribute t.children.length||3!, expecting '"'

JSDOMParser error: Error reading attribute t.children[0].type))return void(t.staticRoot, expecting '"'

JSDOMParser error: Error reading attribute 0);if(t.staticRoot, expecting '"'

JSDOMParser error: Error reading attribute 1,t.children)for(var r, expecting '"'

JSDOMParser error: Error reading attribute ,i, expecting '"'

JSDOMParser error: Error reading attribute .children.length;r<i;r++)e(t.children[r],n||!!t.for);if(t.ifConditions)for(var o, expecting '"'

JSDOMParser error: Error reading attribute ,a, expecting '"'

JSDOMParser error: Error reading attribute .ifConditions.length;o<a;o++)e(t.ifConditions[o].block,n)}}(e,!1))}(n,t);var r, expecting '"'

JSDOMParser error: Error reading attribute a(n,t);return{ast:n,render:r.render,staticRenderFns:r.staticRenderFns}},function(e){function t(t,n){var r, expecting '"'

JSDOMParser error: Error reading attribute bject.create(e),i, expecting '"'

JSDOMParser error: Error reading attribute ],o, expecting '"'

JSDOMParser error: Error reading attribute ];if(n)for(var a in n.modules&&(r.modules, expecting '"'

JSDOMParser error: Error reading attribute e.modules||[]).concat(n.modules)),n.directives&&(r.directives, expecting '"'

JSDOMParser error: Error reading attribute (Object.create(e.directives||null),n.directives)),n)"modules"!, expecting '"'

JSDOMParser error: Error reading attribute a&&"directives"!, expecting '"'

JSDOMParser error: Error reading attribute a&&(r[a], expecting '"'

JSDOMParser error: Error reading attribute [a]);r.warn, expecting '"'

JSDOMParser error: Error reading attribute unction(e,t,n){(n?o:i).push(e)};var s, expecting '"'

JSDOMParser error: Error reading attribute a(t.trim(),r);return s.errors, expecting '"'

JSDOMParser error: Error reading attribute ,s.tips, expecting '"'

JSDOMParser error: Error reading attribute ,s}return{compile:t,compileToFunctions:qa(t)}})(ga),Xa, expecting '"'

JSDOMParser error: Error reading attribute Ga.compile,Ga.compileToFunctions);function Ya(e){return(Za, expecting '"'

JSDOMParser error: Error reading attribute a||document.createElement("div")).innerHTML, expecting '"'

JSDOMParser error: expected '>' to close \

JSDOMParser error: expected '</span>' and got pan>":2

JSDOMParser error: expected '</script>' and got pan>":2==

JSDOMParser error: expected '</body>' and got pan>":2

JSDOMParser error: expected '</html>' and got pan>":2

Error: First argument to Readability constructor should be a document object.
    at new Readability (/Users/jakubriedl/repositories/lrnr/readability/Readability.js:34:11)
    at runReadability (/Users/jakubriedl/repositories/lrnr/readability/test/generate-testcase.js:122:16)
    at /Users/jakubriedl/repositories/lrnr/readability/test/generate-testcase.js:111:5
    at FSReqCallback.oncomplete (node:fs:179:23)
/Users/jakubriedl/repositories/lrnr/readability/test/generate-testcase.js:126
    ex.stack.forEach(console.log.bind(console));
             ^

TypeError: ex.stack.forEach is not a function
    at runReadability (/Users/jakubriedl/repositories/lrnr/readability/test/generate-testcase.js:126:14)
    at /Users/jakubriedl/repositories/lrnr/readability/test/generate-testcase.js:111:5
    at FSReqCallback.oncomplete (node:fs:179:23)
```

**Comment by gijsk** [comment]
This is a bug in the XML serialization helper we're using in the node package (or perhaps in how we use it). It doesn't happen in Firefox when using its XML serializer.

The issue is that there's a script tag in the document where the developer has tried to use CDATA:

```
// <![CDATA[
... script ...
// ]]
```

Now, there are two issues here. First of all, the closing of the CDATA section is missing a `>` anyway, so it wouldn't be valid regardless.
The second is that the elided script here contains this:

```js
(n=n.replace(/<!\--([\s\S]*?)-->/g,"$1").replace(/<!\[CDATA\[([\s\S]*?)]]>/g,"$1"))
```

Which itself contains unescaped cdata markup!

The XML serializer that the node package uses leaves the CDATA section in, and doesn't escape markup (ie `&`, `<` etc.) in it. As a result, the output is no longer valid XML (I think) - the CDATA section ends "early" and the remaining JS doesn't parse as XML (why would it - it's JS!). In Firefox, the XML serializer HTML-escapes the markup inside the would-be CDATA section, and this problem doesn't occur.

The `generate-testcase.js` script doesn't tell you this explicitly, but it leaves the source file it generated on disk, so you can debug what happened, and you can fix up this source file (just remove the entire script tag) and then re-run the script without passing it a URL (ie `node test/generate-testcase.js nymag-1`) and it'll rerun JSDOMParser and readability. This seems to work for me.

I'm not sure what we should do about this off-hand. If there's a way to fix the node XML serialization we should do that... but hopefully this at least unblocks you for what you're doing? :-)

**Comment by jakubriedl** [comment]
it isn't really blocking me, can continue without it. I only wanted to raise it here if it makes some sense fixing. Feel free to close this issue if you don't want to fix it (I don't think it is important to do so).
