### ISSUE TITLE
Parse page got [DOMException [InvalidCharacterError]: """ did not match the Name production]

### ISSUE THREAD

**Issue by akinazuki** [mozilla/readability#773]
I'm trying to parse a page, here is my code
```
import { Readability } from '@mozilla/readability'
import { JSDOM } from 'jsdom';

(async () => {
  try {
    const url = 'https://boerde.lists.lartc.narkive.com/GhiJEp5m/lartc-marking-packets-by-mac-addr-using-tc-filter-u32-match'
    const html = await fetch(url).then((res) => res.text())
    const doc = new JSDOM(html, {
      url,
    })
    const reader = new Readability(doc.window.document)
    const article = reader.parse()

    console.log(article)
  }
  catch (error: any) {
    console.error('Parse failed', error)
  }
})()
```

when i run it will got Error

```
Parse failed [DOMException [InvalidCharacterError]: """ did not match the Name production]
```

my environment is:
```
Node.js v18.7.0
typescript ^4.9.3
jsdom ^20.0.3
@mozilla/readability  ^0.4.2
```

here is the page source which i try to parse: https://pastes.dev/w33pyLHhTw

**Comment by shyamal890** [comment]
Same issue with following url - `https://www.cloudways.com/en/web-hosting-affiliate-program.php`

**Comment by gijsk** [comment]
I think this is a jsdom issue, cf. the stack trace in https://github.com/enzymejs/enzyme/issues/1990:

```
InvalidCharacterError: "" did not match the Name production: Unexpected syntax in top
Line 1:

^^^
    at exports.name (/node_modules/jsdom/lib/jsdom/living/helpers/validate-names.js:11:11)
    at DocumentImpl.createElement (/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:688:5)
    at Document.createElement (/node_modules/jsdom/lib/jsdom/living/generated/Document.js:134:45)
    at createElement (/node_modules/react-dom/cjs/react-dom.development.js:7630:34)
    at createInstance (/node_modules/react-dom/cjs/react-dom.development.js:8714:20)  
```

so I don't think this is something that readability can fix. If this _is_ an issue in readability, please clarify with a stack trace of how you're seeing this in readability.
